# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170109_0900'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articlemodel',
            managers=[
                ('DRAFT', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], max_length=15),
        ),
    ]
