# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 07:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170109_1025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articlemodel',
            managers=[
                ('draft', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
