# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170109_1031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articlemodel',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='published', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
