# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='is_draft',
            field=models.BooleanField(verbose_name='черновик'),
        ),
    ]
