# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20170722_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='html',
            field=models.BooleanField(default=False, verbose_name='Html разметка'),
        ),
        migrations.AlterField(
            model_name='guidemodel',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='черновик'),
        ),
        migrations.AlterField(
            model_name='guidemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
