# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20170722_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterModelTable(
            name='guidemodel',
            table='guide_model',
        ),
    ]
