# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20170723_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidemodel',
            name='end',
        ),
        migrations.RemoveField(
            model_name='guidemodel',
            name='start',
        ),
    ]
