# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20170723_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidemodel',
            name='html',
        ),
    ]
