# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='group_events.GroupEvents'),
        ),
    ]
