# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 20:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20160507_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampreview',
            name='_description_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='streampreview',
            name='description',
            field=precise_bbcode.fields.BBCodeTextField(max_length=300, no_rendered_field=True, validators=[django.core.validators.MinLengthValidator(30)], verbose_name='описание'),
        ),
    ]
