# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_auto_20160511_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampreview',
            name='game_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='игра пользователя'),
        ),
        migrations.AlterField(
            model_name='streampreview',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_preview', to='cat_game.Game', verbose_name='игра'),
        ),
    ]
