# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20160516_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streampreview',
            name='description',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
    ]
