# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-17 20:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_auto_20160529_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampreview',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Hitbox.tv')], null=True, verbose_name='провайдер'),
        ),
        migrations.AddField(
            model_name='streampreview',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='идентификатор'),
        ),
    ]
