# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_auto_20170109_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampreview',
            name='is_postpone',
            field=models.BooleanField(default=False, verbose_name='отсрочить трансляцию'),
        ),
    ]
