# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_groupprofile_num_members'),
        ('stream', '0010_streampreview_is_postpone'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampreview',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_preview', to='group.GroupProfile', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='streamarchive',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Hitbox.tv/Smashcast.tv')], null=True, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='streampreview',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Hitbox.tv/Smashcast.tv')], null=True, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='streamprofile',
            name='provider',
            field=models.IntegerField(choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Hitbox.tv/Smashcast.tv')], verbose_name='провайдер'),
        ),
    ]
