# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_auto_20170509_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamarchive',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Smashcast.tv')], null=True, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='streampreview',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Smashcast.tv')], null=True, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='streamprofile',
            name='provider',
            field=models.IntegerField(choices=[(0, 'Twitch.tv'), (1, 'Youtube.com'), (2, 'Cybergame.tv'), (3, 'Smashcast.tv')], verbose_name='провайдер'),
        ),
    ]
