# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0002_auto_20160517_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
