# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0003_auto_20160518_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-sticky', '-last_post__created', '-created'], 'verbose_name': 'обсуждение', 'verbose_name_plural': 'обсуждения'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='position',
        ),
        migrations.AddField(
            model_name='post',
            name='edited_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
    ]
