# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0004_auto_20160521_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-sticky', 'last_post__created', '-created'], 'verbose_name': 'обсуждение', 'verbose_name_plural': 'обсуждения'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыть'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='sticky',
            field=models.BooleanField(default=False, verbose_name='Закрепить'),
        ),
    ]
