# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0006_auto_20160525_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='group_forum.Topic'),
        ),
    ]
