# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0007_auto_20160525_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group_forum.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_last_post', to='group_forum.Post', verbose_name='Last post'),
        ),
    ]
