# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0009_auto_20160527_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_member_create',
            field=models.BooleanField(default=True, verbose_name='Разрешено создавать'),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_member_edit',
            field=models.BooleanField(default=True, verbose_name='Разрешено редактирование'),
        ),
        migrations.AddField(
            model_name='forum',
            name='num_posts',
            field=models.PositiveIntegerField(default=10, max_length=30, verbose_name='Число комментариев'),
        ),
        migrations.AddField(
            model_name='forum',
            name='num_topics',
            field=models.PositiveIntegerField(default=10, max_length=30, verbose_name='Число обсуждений'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыть форум'),
        ),
    ]
