# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0010_auto_20160527_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='num_posts',
            field=models.PositiveIntegerField(default=10, verbose_name='Число комментариев'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='num_topics',
            field=models.PositiveIntegerField(default=10, verbose_name='Число обсуждений'),
        ),
    ]
