# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0011_auto_20160527_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AddField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='num_posts',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Число комментариев'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='num_topics',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Число обсуждений'),
        ),
    ]
