# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0012_auto_20160529_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'created', 'ordering': ['-sticky', '-last_post__created'], 'verbose_name': 'обсуждение', 'verbose_name_plural': 'обсуждения'},
        ),
    ]
