# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0013_auto_20160530_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_topics', models.PositiveSmallIntegerField(default=10, verbose_name='Число обсуждений')),
                ('num_posts', models.PositiveSmallIntegerField(default=10, verbose_name='Число комментариев')),
                ('is_member_edit', models.BooleanField(default=False, verbose_name='Разрешено редактирование посты')),
                ('is_member_create', models.BooleanField(default=True, verbose_name='Разрешено создавать темы')),
                ('is_last_post_top', models.BooleanField(default=False, verbose_name='Последний пост сверху')),
            ],
            options={
                'verbose_name': 'настройки форума',
                'verbose_name_plural': 'настройки форумов',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='is_member_create',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='is_member_edit',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='num_posts',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='num_topics',
        ),
        migrations.AlterField(
            model_name='forum',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='group.GroupProfile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='group_forum.Settings'),
        ),
    ]
