# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_forum', '0014_auto_20160617_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_post_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_last_post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
