# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0015_topic_last_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='is_last_post_top',
            new_name='post_ordering',
        ),
    ]
