# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_forum', '0016_auto_20160618_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='send_response',
            field=models.BooleanField(default=False, verbose_name='подписаться на обсуждение'),
        ),
    ]
