# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20160201_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='background', verbose_name='фон'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='cat_game.Game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Группа'), (1, 'Отряд'), (2, 'Команда'), (3, 'Клан'), (4, 'Гильдия'), (5, 'Клуб')], verbose_name='тип'),
        ),
    ]
