# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20160509_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='_description_rendered',
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(30)], verbose_name='описание'),
        ),
    ]
