# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 09:33
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20160511_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='background', verbose_name='баннер'),
        ),
    ]
