# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20160531_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='game_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='игра группы'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='backgrounds', verbose_name='баннер'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='описание'),
        ),
    ]
