# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20160605_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'ordering': ['created', 'name'], 'verbose_name': 'клан', 'verbose_name_plural': 'кланы'},
        ),
        migrations.AlterField(
            model_name='groupmoderator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_moderator', to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
    ]
