# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20161024_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmoderator',
            unique_together=set([('user', 'group')]),
        ),
    ]
