# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20161024_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=set([('recipient', 'group')]),
        ),
    ]
