# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20170117_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvite',
            options={'ordering': ['-send_ts'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='type',
            field=models.IntegerField(choices=[(0, 'Приглашение'), (1, 'Заявка')], default=0, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to=settings.AUTH_USER_MODEL, verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(max_length=600, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Группа'), (1, 'Отряд'), (2, 'Команда'), (3, 'Клан'), (4, 'Гильдия'), (5, 'Клуб'), (6, 'Легион')], verbose_name='тип'),
        ),
    ]
