# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0016_auto_20170120_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=set([('recipient', 'group', 'type')]),
        ),
    ]
