# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_auto_20170120_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='num_members',
            field=models.IntegerField(default=0),
        ),
    ]
