# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:25
from __future__ import unicode_literals

from django.db import migrations
import group.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_groupprofile_num_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=group.models.background_directory_path, verbose_name='фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='emblem',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=group.models.emblems_directory_path, verbose_name='эмблема'),
        ),
    ]
