# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='crop',
            field=models.IntegerField(choices=[(0, 'center'), (1, 'top'), (2, 'bottom'), (3, 'right'), (4, 'left')], default=0, null=True, verbose_name='обрезка'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='quality',
            field=models.PositiveIntegerField(blank=True, default=80, null=True, verbose_name='качество'),
        ),
    ]
