# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 06:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20160531_2003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='slidermodel',
            managers=[
                ('draft', django.db.models.manager.Manager()),
            ],
        ),
    ]
