# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_auto_20170117_1030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='slidermodel',
            managers=[
            ],
        ),
    ]
