# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:25
from __future__ import unicode_literals

from django.db import migrations
import slider.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_auto_20170117_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=slider.models.slider_directory_path, verbose_name='фон'),
        ),
    ]
