# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_auto_20170805_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='видео'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='сылка на видео'),
        ),
    ]
