# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20160510_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='_description_rendered',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='о себе'),
        ),
    ]
