# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='модератор'),
        ),
    ]
