# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='о себе'),
        ),
    ]
