# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20160605_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userbar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='подпись на форуме'),
        ),
    ]
