# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cat_game', '0001_initial'),
        ('user_profile', '0008_userprofile_userbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='имя')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_character', to='cat_game.Game', verbose_name='игра')),
            ],
            options={
                'verbose_name_plural': 'игровые персонажи',
                'verbose_name': 'игровой персонаж',
                'db_table': 'game_character',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='game_user',
        ),
        migrations.AddField(
            model_name='gamecharacter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_characters', to=settings.AUTH_USER_MODEL, verbose_name='пользовательский профиль'),
        ),
    ]
