# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20160605_2233'),
        ('user_profile', '0009_auto_20161013_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecharacter',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_characters', to='group.GroupProfile', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_characters', to='cat_game.Game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='gamecharacter',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
    ]
