# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-02 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20161014_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_moderator',
        ),
    ]
