# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_game', '0003_auto_20170809_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
    ]
